version: '3.8'

services:
  exchange-info:
    build: .
    container_name: exchange-info-collector
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # 挂载数据目录，确保数据持久化
      - ./data:/app/data
      # 挂载配置文件，方便修改Telegram配置
      - ./telegram_config.py:/app/telegram_config.py:ro
      # 挂载日志目录
      - ./logs:/app/logs
    networks:
      - exchange-network

  # 可选：添加定时任务服务
  cron:
    image: alpine:latest
    container_name: exchange-info-cron
    restart: unless-stopped
    volumes:
      - ./crontab:/etc/crontabs/root
      - ./data:/app/data
    command: crond -f -d 8
    depends_on:
      - exchange-info
    networks:
      - exchange-network

networks:
  exchange-network:
    driver: bridge

volumes:
  data:
    driver: local 